spring.application.name=ZonaFit_Spring
spring.datasource.url=jdbc:mysql://localhost:3306/zona_fit_db
spring.datasource.username=root
spring.datasource.password=$SutFRVvpjlsLrop*5Q3i$ncO$#8zpz8S&!x53Cjny@TWWlOj4
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#Nos conectamos a la base de datos jeje y evitamos la creacion del esquema de la bd 
spring.jpa.hibernate.ddl-auto=none
#quiero que me muestre las sentencias sql por si acaso
spring.jpa.show-sql=true
#desactivar tomcat porque esto no es web
spring.main.web-application-type=none